buildscript {
    repositories {
        mavenLocal()
        mavenCentral()
        maven { url = 'https://repo.grails.org/grails/restricted' }
    }
    dependencies {
        classpath platform("org.apache.grails:grails-bom:$grailsVersion")
        classpath "org.apache.grails:grails-gradle-plugins"
        classpath "cloud.wondrify:asset-pipeline-gradle"
    }
}

apply plugin: "groovy"
apply plugin: "idea"
apply plugin: "eclipse"
apply plugin: "war"
apply plugin: "application"
apply plugin: "org.apache.grails.gradle.grails-web"
apply plugin: "org.apache.grails.gradle.grails-gsp"
apply plugin: "cloud.wondrify.asset-pipeline"

group = "hibernate.filter.example"

repositories {
    mavenLocal()
    mavenCentral()
    maven { url = 'https://repo.grails.org/grails/restricted' }
}

dependencies {
    implementation platform("org.apache.grails:grails-bom:$grailsVersion")

    implementation project(':hibernate-filter-plugin')

    implementation "org.apache.grails:grails-core"
    implementation "org.apache.grails:grails-logging"
    implementation "org.apache.grails:grails-databinding"
    implementation "org.apache.grails:grails-interceptors"
    implementation "org.apache.grails:grails-rest-transforms"
    implementation "org.apache.grails:grails-services"
    implementation "org.apache.grails:grails-url-mappings"
    implementation "org.apache.grails:grails-web-boot"
    implementation "org.apache.grails:grails-gsp"
    implementation "org.apache.grails:grails-data-hibernate5"
    implementation "org.apache.grails:grails-scaffolding"
    implementation "org.hibernate:hibernate-core-jakarta"
    implementation "org.springframework.boot:spring-boot-autoconfigure"
    implementation "org.springframework.boot:spring-boot-starter"
    implementation "org.springframework.boot:spring-boot-starter-actuator"
    implementation "org.springframework.boot:spring-boot-starter-logging"
    implementation "org.springframework.boot:spring-boot-starter-tomcat"
    implementation "org.springframework.boot:spring-boot-starter-validation"

    console "org.apache.grails:grails-console"
    assets  "org.apache.grails:grails-dependencies-assets"

    runtimeOnly "com.h2database:h2"
    runtimeOnly "org.apache.tomcat:tomcat-jdbc"
    runtimeOnly "org.fusesource.jansi:jansi"

    testImplementation "org.apache.grails.testing:grails-testing-support-core"
    testImplementation "org.apache.grails:grails-testing-support-datamapping"
    testImplementation "org.apache.grails:grails-testing-support-web"
    testImplementation "org.spockframework:spock-core"
    testImplementation "net.bytebuddy:byte-buddy"
    testRuntimeOnly    "net.bytebuddy:byte-buddy-agent"
}

application {
    mainClass.set("hibernate.filter.example.Application")
}

compileJava.options.release = 17

// https://github.com/apache/grails-core/issues/15321
tasks.withType(GroovyCompile).configureEach {
    groovyOptions.optimizationOptions.indy = false
    groovyOptions.forkOptions.jvmArgs = ['-Xmx1024m']
}

bootRun {
    ignoreExitValue true
    jvmArgs('-Dspring.output.ansi.enabled=always', '-XX:TieredStopAtLevel=1', '-Xmx1024m')
    sourceResources sourceSets.main
    String springProfilesActive = 'spring.profiles.active'
    systemProperty springProfilesActive, System.getProperty(springProfilesActive)
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}

assets {
    minifyJs = true
    minifyCss = true
}
